---
title: "Introduction/hypothesis"
author: "Phoebe Lin"
date: "2023-12-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Introduction:

Police have existed in America in some form for nearly its entire history. Police forces themselves have their philosophical origin in Patrick Colquhoun's 1797 "Treatise on the Police of the Metropolis." These ideas first took form in London in 1829, but Colquhoun himself spent his early career as a British agent for cotton manufacturers. His conception of policing grew from his time spent enforcing slave codes and working with slave patrols in Virginia. The first hiring of police through legislative means was in Boston in 1838, but  before then "police" simply referred to slave patrols. North Carolina's first state police force was formed in order to stamp out the publishing of "The Liberator," William Lloyd Garrison's weekly abolitionist newspaper, soon after he was almost killed in a mob attack in Boston in 1835. The modern American police force began and grew from these dark roots of American history.

The existing literature around racialized policing has established that Black, Hispanic and American Indian/Native Americans are disproportionately likely to be killed by police in America, especially at younger ages. One study using data from between 2013 and 2018 found that Black men are ~2.5 times more and Black women ~1.4 times more likely to be killed by police in their lifetime than white men and white women, respectively. This amounts to some 96 out of 100,000 Black men and boys, between 36 and 81 American Indian/Alaskan Native men and boys, and 53 out of 100,000 Latino men and boys being killed by police over their lifetime, as compared to about 39 out of 100,000 white men and boys being killed. The risk is substantially lower for women across all racial groups. Between 2.4 and 5.4 Black women and girls, 2.4 American Indian/Alaskan Native women and girls, and 2 Latino and white women and girls out of 100,000 are expected to be killed by police throughout their lifetime. 

In the past decade, the Black Lives Matter Movement rose up in this context and caused the public to emerge as a strong force to fight for racial justice and equality in the United States. This movement sparked a conversation around the appropriate use of force by the police. The public began pushing for more transparency around the use of force, and policing general (Schwartz, 2020). That demand has been met, to an extent, and today we have detailed data on the use of force by many police departments in the US. In DC, specifically, previous research has used this research to establish that the majority of citizen-police interactions involve Black residents and these individuals were much more likely to be stopped and frisked than white residents (Golash-Boza, T. Et al, 2022).

In our analysis of police use of force in different U.S. cities during 2020, with a focus on Washington D.C., we build upon the findings of Edwards, Lee, and Esposito's 2019 study on the risk of fatal police encounters across various demographics. The paper provides a comprehensive analysis of the risk of fatal encounters with police across different demographic groups in the United States. It utilizes data from 2013 to 2018 to assess the likelihood of such incidents, focusing on variations by race, age, and gender.Their research, crucial in highlighting national disparities in police violence, does not employ regression analysis. By integrating regression models in our study, we aim to provide a more refined understanding of these dynamics, especially in the context of local data. This approach allows us to explore the intricacies of police-citizen interactions and use of force in specific urban settings, adding depth to the national perspective offered by Edwards et al.

In this study, we collected the use of force data from four different cities, which are Washington D.C., Seattle, Washington, Portland, and Indianapolis and will be focusing on the data in year 2020. But overall, we will focus more on Washington D.C. and other cities will be used as a consideration to compare and contrast. Since in each datasets, it includes over 15 columns, therefore, we branched down to several particles, one focused on the officer race and see the total number of use of force counts for each subject race to observe whether overusing of use of force is happening. 

Hypothesis:

Our hypothesis posits that Black people are overrepresented in police use of force incidents in the four cities studied, especially in Washington D.C. This is supported by the historical background of American policing, which has roots in enforcing slave codes and racialized practices. Studies, such as the one by Edwards, Lee, and Esposito, highlight racial disparities in fatal police encounters, particularly affecting Black, Hispanic, and American Indian/Native American communities. These insights, combined with recent public demands for transparency in policing, underscore our hypothesis. By applying regression analysis to 2020 data, we aim to provide a more detailed examination of these racial disparities in specific urban settings, contributing to the ongoing discourse on racial justice and policing.

Data-driven hypothesis:

Our data-driven hypothesis, informed by preliminary data analysis, suggests a significant racial disparity in police use of force, particularly against the Black/African American community in Washington D.C, Seattle, Washington and Indianapolis, Indiana. This disparity is evident in the higher counts of use of force incidents involving Black individuals compared to other racial groups. Additionally, white officers appear to use force more frequently than officers of other races. In contrast, Portland's data shows the highest counts of incidents involving white individuals, likely reflecting the city's demographic composition. Through multivariate multiple regression models, we aim to predict various aspects of use of force incidents, anticipating that subject race, police district, and officer race will be significant predictors. The model will help us understand the extent to which these factors influence the use of force, with a particular focus on the racial dynamics within the context of a majority Black police force in D.C.


Some new citations:

Conner, A., Azrael, D., Lyons, V. H., Barber, C., & Miller, M. (2019). Validating the National Violent Death Reporting System as a Source of Data on Fatal Shootings of Civilians by Law Enforcement Officers. American journal of public health, 109(4), 578–584. https://doi.org/10.2105/AJPH.2018.304904
